### PR TITLE
add responsiveness in Dashboard

### PR DESCRIPTION
**Pull request by SandipM03**
"I have made all the necessary changes. Can you please check it?

### CODE REVIEW

**Comment by divyaagrawal261** [comment]
> "I have made all the necessary changes. Can you please check it?

Please provide the link to the deployed version to make the verification easier!

**Comment by SandipM03** [comment]
Hello @divyaagrawal261, thanks for your reply. I will upload a video of the dashboard page for better verification.

https://github.com/user-attachments/assets/383f532a-2c65-42cf-bdac-ebfc52c7ee7a

**Comment by divyaagrawal261** [comment]
Sorry, I like the previous version!

**Comment by SandipM03** [comment]
Alright, thanks for your replay

**Pull request closed without merging**
